version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=KinMKD
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgres

  app:
    image: kinmkd
    depends_on:
      - postgres
    build: ./
    restart: on-failure
    ports:
      - '6868:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/KinMKD
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
